### ISSUE TITLE
BUG D'EXPORT DE CFG 

### ISSUE THREAD

**Issue by azer940** [Road-hog123/Blender-OMSI-Exporter#19]
bonjour quand j'essaye d'import un cfg par exemple des nouveaux urbanway step e j'ai l'erreur suivant :

Python: Traceback (most recent call last):
  File "C:\Users\arda\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Blender-O3D-IO-Public\__init__.py", line 133, in execute
    io_o3d_import.do_import(self.filepath, context, self.import_x, self.override_text_encoding, self.hide_lods)
  File "C:\Users\arda\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Blender-O3D-IO-Public\o3d_io\io_o3d_import.py", line 51, in do_import
    (cfg_data, obj_root) = read_cfg(filepath, override_text_encoding)
  File "C:\Users\arda\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Blender-O3D-IO-Public\o3d_io\o3d_cfg_parser.py", line 272, in read_cfg
    light_flare["cone_effect"] = int(line) == 1
ValueError: invalid literal for int() with base 10: '0.1'

Python: Traceback (most recent call last):
  File "C:\Users\arda\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Blender-O3D-IO-Public\__init__.py", line 133, in execute
    io_o3d_import.do_import(self.filepath, context, self.import_x, self.override_text_encoding, self.hide_lods)
  File "C:\Users\arda\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Blender-O3D-IO-Public\o3d_io\io_o3d_import.py", line 51, in do_import
    (cfg_data, obj_root) = read_cfg(filepath, override_text_encoding)
  File "C:\Users\arda\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Blender-O3D-IO-Public\o3d_io\o3d_cfg_parser.py", line 272, in read_cfg
    light_flare["cone_effect"] = int(line) == 1
ValueError: invalid literal for int() with base 10: '0.1'

j'aimerai bien avoir la résolution de beug si possible 

cordialement

**Comment by Road-hog123** [comment]
Ceci n'est pas [Blender-O3D-IO-Public](https://github.com/space928/Blender-O3D-IO-Public)
