### ISSUE TITLE
Bug on addon

### ISSUE THREAD

**Issue by Rashford0319** [Road-hog123/Blender-OMSI-Exporter#8]
## Bug Description
The addon cannot be enabled.

## Steps to Reproduce
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\sotho\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_export_o3d\__init__.py", line 39, in <module>
    from .exporter import Exporter
  File "C:\Users\sotho\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_export_o3d\exporter.py", line 63
    def __init__(self, /, *,

## Version Information
 - Blender: 3.4.1
 - Exporter: 3.1.0

**Comment by Road-hog123** [comment]
@Rashford0319 I take it you've resolved this issue yourself?
